spring:
  webflux:
    base-path: /template
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:pool:mssql://localhost:1433/loan
    username: sa
    password: P@ssw0rd
  cloud:
    discovery:
      enabled: false
    config:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    homePageUrl: "http://${eureka.hostname}:2099/template/" # update port, replace 'template'

server:
  port: 2099

